### Numpy 

In [1]:
#importing numpy
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9])

### Attributes of numpy

In [3]:
arr.dtype

dtype('int32')

In [4]:
arr.ndim

1

In [5]:
arr.size

9

In [6]:
arr.shape

(9,)

In [7]:
arr[2]

3

## Multi Diamensional Array

In [8]:
arr1=np.array([[2,1,3,],[1,2,3]])

In [9]:
arr1.shape

(2, 3)

In [10]:
arr1.size

6

In [11]:
arr1.ndim

2

In [12]:
arr1[0,2]

3

In [13]:
arr1[1,0]

1

In [14]:
arr4 = np.array([[[[[1,2,3,4,5,6,7,8,9]]]]])

In [15]:
arr4[0,0,0,0,2]

3

In [16]:
arr1=np.array([[2,1,3,],[1,2,3]],dtype= float)
arr1

array([[2., 1., 3.],
       [1., 2., 3.]])

## bigger array

In [17]:
arr2=np.array([[1,2,3,4],[5,6,7,8],
               [9,10,11,12], [13,14,15,16],
              [17,18,19,20],[21,22,23,24],[25,26,27,28]],dtype=float)
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.],
       [17., 18., 19., 20.],
       [21., 22., 23., 24.],
       [25., 26., 27., 28.]])

In [18]:
arr2.shape

(7, 4)

In [19]:
arr2.size

28

In [20]:
arr2.ndim

2

In [21]:
arr2[2][2]

11.0

In [22]:
arr3=np.full((3,4,5),7)
arr3

array([[[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]],

       [[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]],

       [[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]]])

In [23]:
arr4=np.zeros((3,3))
arr4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
arr5=np.ones((3,4,5))
arr5

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

### empty and random

In [25]:
arr6=np.empty((4,4))
arr6

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.33646845e-307],
       [1.11256817e-306, 1.06811422e-306, 1.42417221e-306,
        1.11260619e-306],
       [8.90094053e-307, 1.86919378e-306, 1.06809792e-306,
        1.37962456e-306],
       [1.69111861e-306, 1.78020169e-306, 1.37961777e-306,
        7.56599807e-307]])

In [26]:
arr7=np.random.random((2,2))
arr7

array([[0.79595741, 0.78134424],
       [0.50762263, 0.41461852]])

In [27]:
arr7.ndim

2

In [28]:
arr7.size

4

In [29]:
arr8=np.arange(10,50,5)
arr8

array([10, 15, 20, 25, 30, 35, 40, 45])

In [31]:
b_linespace=np.linspace(0,50,2)
b_linespace

array([ 0., 50.])

In [32]:
b_linespace.ndim

1

In [33]:
b_linespace.size

2

In [34]:
b_linespace1=np.linspace(0,50,30)
b_linespace1

array([ 0.        ,  1.72413793,  3.44827586,  5.17241379,  6.89655172,
        8.62068966, 10.34482759, 12.06896552, 13.79310345, 15.51724138,
       17.24137931, 18.96551724, 20.68965517, 22.4137931 , 24.13793103,
       25.86206897, 27.5862069 , 29.31034483, 31.03448276, 32.75862069,
       34.48275862, 36.20689655, 37.93103448, 39.65517241, 41.37931034,
       43.10344828, 44.82758621, 46.55172414, 48.27586207, 50.        ])

In [35]:
b_linespace1=np.linspace(0,50,30,dtype=int)
b_linespace1

array([ 0,  1,  3,  5,  6,  8, 10, 12, 13, 15, 17, 18, 20, 22, 24, 25, 27,
       29, 31, 32, 34, 36, 37, 39, 41, 43, 44, 46, 48, 50])

In [38]:
b_linespace1=np.exp(3)
b_linespace1

20.085536923187668

In [39]:
b_linespace1=np.sin(1)
b_linespace1

0.8414709848078965

In [40]:
b_linespace1=np.cos(3)
b_linespace1

-0.9899924966004454

In [41]:
b_linespace1=np.tan(5)
b_linespace1

-3.380515006246586

In [42]:
b_linespace1=np.sqrt(31)
b_linespace1

5.5677643628300215